import type { Metadata } from "next";
import "@/app/globals.css";
import RegHeader
 from "@/screens/courier/registration/components/RegHeader";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
     <RegHeader/>
      {children}
    </div>
  );
}